controller_manager_ns: controller_manager
# Load joint trajectory controller
controller_list:
  - name: arm_manipulator_controller
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - BJ
      - SJ
      - EJ
      - W1J
      - W2J
      - W3J

  # - name: gripper_manipulator_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   joints:
  #     - finger_joint1
  #     - finger_joint2