controller_list:
  - name: fake_arm_manipulator_controller
    joints:
      - BJ
      - SJ
      - EJ
      - W1J
      - W2J
      - W3J
  - name: fake_gripper_manipulator_controller
    joints:
      - finger_joint1
      - finger_joint2