controller_list:
  - name: fake_arm_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - BJ
      - SJ
      - EJ
      - W1J
      - W2J
      - W3J
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - finger_joint
initial:  # Define initial robot poses per group
  - group: arm_manipulator
    pose: UP
  - group: gripper
    pose: OPEN