# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# max_velocity is 38rpm for big motors and 42rpm for small motors at 48V
# 1 rpm = 0.10472 rad/s
joint_limits:
  BJ:
    min_position: -2.0944
    max_position: 2.0944
    has_velocity_limits: true
    # max_velocity: 3.97936 # rad/s 
    max_velocity: 5.0 # rad/s 
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 0

  SJ:
    min_position: -1.5708
    max_position: 1.5708
    has_velocity_limits: true
    # max_velocity: 3.97936 # rad/s
    max_velocity: 5.0 # rad/s
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 0

  EJ:
    min_position: -3.92699
    max_position: 1.0472
    has_velocity_limits: true
    # max_velocity: 3.97936 # rad/s
    max_velocity: 5.0 # rad/s
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 0
  
  W1J:
    min_position: -1.5708
    max_position: 1.5708
    has_velocity_limits: true
    # max_velocity: 4.39824 # rad/s
    max_velocity: 5.0 # rad/s
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 0

  W2J:
    min_position: -1.0472
    max_position: 2.618
    has_velocity_limits: true
    # max_velocity: 4.39824 # rad/s
    max_velocity: 5.0 # rad/s
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 0
    
  W3J:
    min_position: -3.14159
    max_position: 3.14159
    has_velocity_limits: true
    # max_velocity: 4.39824 # rad/s
    max_velocity: 5.0 # rad/s
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 0