gazebo_ros_control/pid_gains:
  BJ: {p: 100,  d: 0.2, i: 100}
  SJ: {p: 100,  d: 1.0, i: 200}
  EJ: {p: 100,  d: 0.2, i: 100}
  W1J: {p: 100,  d: 0.2, i: 100}
  W2J: {p: 100,  d: 0.2, i: 100}
  W3J: {p: 100,  d: 0.2, i: 100}
